---
- name: Pull container images
  hosts: all
  gather_facts: false

  vars:
    images:
      - barbican
      - cinder
      - common
      - designate
      - glance
      - grafana
      - heat
      - horizon
      - keystone
      - loadbalancer
      - mariadb
      - memcached
      - neutron
      - nova
      - octavia
      - opensearch
      - openvswitch
      - ovn
      - placement
      - prometheus
      - rabbitmq
      - redis
      - skyline

  tasks:
    - name: Pull kolla images
      ansible.builtin.command:
        cmd: "osism apply -r 2 -a pull {{ item }}"
      environment:
        INTERACTIVE: "false"
      loop: "{{ images }}"
      changed_when: true

    - name: Pull container images
      community.docker.docker_image:
        name: "{{ item }}"
        source: pull
      loop:
        # Only container images used in plays that do not offer a dedicated pull action are listed here.
        - "{{ ceph_docker_registry }}/{{ ceph_docker_image }}:{{ ceph_image_version }}"
        - "{{ docker_registry_cephclient }}/osism/cephclient:{{ cephclient_version }}"
        - "{{ docker_registry_openstackclient }}/osism/openstackclient:{{ openstackclient_version }}"
