---
- name: Apply cloud-in-a-box specific workarounds
  hosts: all
  gather_facts: false

  tasks:
    - name: Copy /etc/issue file
      become: true
      ansible.builtin.copy:
        src: issue
        dest: /etc/issue
        mode: 0644
        owner: root
        group: root

    - name: Copy workarounds.sh scripts
      become: true
      ansible.builtin.template:
        src: workarounds.sh.j2
        dest: /usr/local/bin/workarounds.sh
        mode: 0755
        owner: root
        group: root

    - name: Copy workarounds systemd unit file
      become: true
      ansible.builtin.template:
        src: workarounds.service.j2
        dest: /etc/systemd/system/workarounds.service
        mode: 0644
        owner: root
        group: root

    - name: Reload systemd daemon
      become: true
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Enable workarounds.service
      become: true
      ansible.builtin.service:
        name: workarounds
        enabled: true
