---
- job:
    name: abstract-cloud-in-a-box
    abstract: true
    nodeset: ubuntu-noble-large
    run: playbooks/run.yml
    timeout: 10800

- job:
    name: cloud-in-a-box-kubernetes
    parent: abstract-cloud-in-a-box
    vars:
      cloud_in_a_box_type: kubernetes

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - ansible-lint
        - yamllint
    periodic-daily:
      jobs:
        - ansible-lint
        - yamllint
