---
- hosts: localhost
  name: Create manager cert for cloud-in-a-box
  gather_facts: false
  vars_prompt:
    - name: Set secret_ca_passphrase
      prompt: Enter secret_ca_passphrase

  tasks:
    - name: Create private key for new manager certificate  # noqa: run-once[task]
      community.crypto.openssl_privatekey:
        path: cloud-in-a-box-manager.key
      run_once: true

    - name: Create certificate signing request (CSR) for new manager certificate  # noqa: run-once[task]
      community.crypto.openssl_csr_pipe:
        privatekey_path: cloud-in-a-box-manager.key
        subject_alt_name:
          - "DNS:manager.systems.in-a-box.cloud"
          - "IP:192.168.16.10"
      run_once: true
      register: csr

    - name: Sign manager certificate with our CA  # noqa: run-once[task]
      community.crypto.x509_certificate_pipe:
        csr_content: "{{ csr.csr }}"
        provider: ownca
        ownca_path: cloud-in-a-box-ca-certificate.pem
        ownca_privatekey_path: cloud-in-a-box-ca-certificate.key
        ownca_privatekey_passphrase: "{{ secret_ca_passphrase }}"
        ownca_not_after: +3650d  # valid for ten years
        ownca_not_before: "-1h"  # valid since one hour
      run_once: true
      register: certificate

    - name: Write manager certificate file  # noqa: run-once[task]
      ansible.builtin.copy:
        dest: cloud-in-a-box-manager.pem
        content: "{{ certificate.certificate }}"
        mode: 0640
      run_once: true
