---
- name: Run cloud-in-a-box
  hosts: all

  vars:
    cloud_in_a_box_type: sandbox

  tasks:
    - name: Create cloud-in-a-box directory
      become: true
      ansible.builtin.file:
        path: /opt/cloud-in-a-box
        state: directory
        mode: 0755

    - name: Sync cloud-in-a-box directory  # noqa: command-instead-of-module
      become: true
      ansible.builtin.command: "rsync -avz {{ ansible_user_dir }}/{{ zuul.project.src_dir }}/ /opt/cloud-in-a-box"
      changed_when: true

    - name: Run cleanup script
      become: true
      ansible.builtin.command: /opt/cloud-in-a-box/cleanup.sh
      changed_when: true

    - name: Upgrade packages
      become: true
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist

    - name: Create osism user
      become: true
      ansible.builtin.user:
        name: osism
        update_password: always
        password: "!"
        password_lock: true

    - name: Set ssh authorized keys of the osism user
      become: true
      ansible.posix.authorized_key:
        key: "{{ item }}"
        user: osism
      loop:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDIquLz7xZ1rzpsoivjOiZTarg+jri0ezRn823wGw4G0gFfosxPxNJ4BS1LaGjje9YI4JVsU2btDuxcNIvmRehVLPHxRwpDHE+FVajltnF1DQXiySitdbC27N1NIaVbWv8y1C2PFnXL+QUrF2VddOzNnMBXingEV2Ev/bTW/XfVTTArpHsNTS0DJRMpMeUROHmCwxhWjjuFfCcH2EEn5KyBCvgiQIozkwf5Q7nK3DeG2QODxtLPJkmCEuvpqbwZF8VkaE1n1TLr7a9CD/p4sn1+Z1BJO+Zsg72AM9A0lKQ0/1TCsAHLMIoZoNH2F7JeNtApFhDAEg9EZGyk0RDkrKxojYzuimvoyYXI84JDdKx3kDFGiXB3ITDMOFRajGLdgJwAZT2Aw62H0uWQs1dMNRtMgaemLIDmschZDVH5j9iDwEZaKVzJ6LLDSn1Wl09nuZNV8okNIvsBe4X6mHzqwLOYYga/HmI6y4nudTLSeckFraMXGRFFfGHDVpNwKRRavx0= dragon@osism

    - name: Create osism sudoers file
      become: true
      ansible.builtin.copy:
        content: |
          osism ALL=(ALL:ALL) NOPASSWD:ALL
        dest: /etc/sudoers.d/osism
        owner: root
        group: root
        mode: 0644

    - name: Run bootstrap script
      become: true
      ansible.builtin.command: "/opt/cloud-in-a-box/bootstrap.sh {{ cloud_in_a_box_type }}"
      changed_when: true
